using LibraryManagement.BusinessLogic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;

namespace LibraryManagement.WebApi.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class LibraryController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<LibraryController> _logger;

        public LibraryController(ILogger<LibraryController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IEnumerable<Person> Get()
        {
            var rng = new Random();

            _logger.LogInformation("[Random person sent]");

            return Enumerable.Range(1, 5).Select(index => new Person
            {
                Email = "autogenerated@vlad.com",
                Address = null,
                Phone = rng.Next(-20, 55).ToString(),
                Name = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray();            
        }
    }
}
